---
- name: Red Hat Insights Events Rulebook
  hosts: all
  sources:
   - redhatinsights.eda.insights:
       host: "0.0.0.0"
       port: "5000"
       token: "{{ secret_token }}"
  rules:
    - name: Log All Insights Events
      condition: event.payload is defined
      action:
        debug:
          msg: >
            "Received Insights event: {{ event.payload | to_nice_json }}"
