---
- name: Red Hat Insights Events Rulebook
  hosts: all
  sources:
   - redhatinsights.eda.insights:
       host: "0.0.0.0"
       port: "5000"
       token: "{{ secret_token }}"
  rules:
    - name: Match Test event
      condition: 
        event.payload.application == "Test application" and event.payload.event_type == "Test event"
      action:
        run_job_template:
          name: "Create ServiceNow Incident"
          organization: Default
          job_args: 
            extra_vars: "{{ event }}"
    - name: Log All Insights Events
      condition: event.payload is defined
      action:
        debug:
          msg: >
            "Received Insights event: {{ event.payload | string }}"
