---
- name: Red Hat Insights Events Rulebook
  hosts: all
  sources:
    - redhat.insights_eda.insights:
        host: 0.0.0.0
        port: 5000
        token: "{{ SECRET_TOKEN }}"
  rules:
    - name: Log All Insights Events
      condition: event.payload is defined
      action:
        debug:
          msg: >
            "Received Insights event: {{ event.payload | to_json }}"
