---
- name: Red Hat Insights Events Rulebook
  hosts: all
  sources:
   - ansible.eda.webhook:
       host: "{{ eda_webhook_host }}"
       port: "{{ eda_webhook_port }}"
  rules:
    - name: Log All Insights Events
      condition: event.payload is defined
      action:
        debug:
          msg: >
            "Received Insights event: {{ event.payload | to_json }}"
