- name: Create an Incident
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        state: new
        short_description: "{{ event.payload.application | upper | default('') }}"
        description: |-
          impact: low
          urgency: low
          Account id: "{{ event.payload.account_id | default('') }}"
          Affected system: "{{ event.payload.context.display_name | default('') }}"
          Event type: "{{ event.payload.event_type | default('') }}"
          Bundle: "{{ event.payload.bundle | default('') }}"
          Created at: "{{ event.payload.timestamp | default('') }}"
