- name: Create an Incident
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: payload
      prompt: ""
      private: false
  tasks:
    - name: Dump all received variables
      debug:
        var: vars
    - name: Create the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        state: new
        caller: "{{ sn_user }}"
        impact: low
        urgency: low
        short_description: "{{ payload.application | upper | default('') }}"
#        description: |-
#          impact: low
#          urgency: low
#          Account id: "{{ payload.account_id | default('') }}"
#          Affected system: "{{ payload.context.display_name | default('') }}"
#          Event type: "{{ payload.event_type | default('') }}"
#          Bundle: "{{ payload.bundle | default('') }}"
#          Created at: "{{ payload.timestamp | default('') }}"
        incident_mapping:
          close_code:
            "": ""
      register: created
    - name: Append text to Additional comments
      servicenow.itsm.api:
        instance:
          host:     "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        resource:  incident
        action:    patch
        sys_id:    "{{ created.record.sys_id }}"
        data:
          comments: |
            Impact:   low
            Urgency:  low
            Account ID:        {{ payload.account_id   | default('') }}
            Affected system:   {{ payload.context.display_name | default('') }}
            Event type:        {{ payload.event_type | default('') }}
            Bundle:            {{ payload.bundle | default('') }}
            Created at:        {{ payload.timestamp | default('') }}
      when: created.record.sys_id is defined
      register: add_comments
    - name: Verify final Description
      debug:
        msg: |
          ✔ Created {{ created.record.number }} (sys_id={{ created.record.sys_id }})
