- name: Create an Incident
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: application
      prompt: ""
      private: false
  tasks:
    - name: Dump all received variables
      debug:
        var: vars
    - name: Create the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        state: new
        short_description: "{{ payload.application | upper | default('') }}"
        description: |-
          impact: low
          urgency: low
          Account id: "{{ account_id | default('') }}"
          Affected system: "{{ context.display_name | default('') }}"
          Event type: "{{ event_type | default('') }}"
          Bundle: "{{ bundle | default('') }}"
          Created at: "{{ timestamp | default('') }}"
