- name: Create an Incident
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: payload
      prompt: ""
      private: false
  tasks:
    - name: Dump all received variables
      debug:
        var: vars
    - name: Create the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        state: new
        caller: "{{ sn_user }}"
        impact: low
        urgency: low
        short_description: "{{ payload.application | upper | default('') }}"
        description: >
      "\"impact: low\nurgency: low\nAccount id: {{ payload.account_id | default('') }}\nAffected system: {{ payload.context.display_name | default('') }}\nEvent type: {{ payload.event_type | default('') }}\nBundle: {{ payload.bundle | default('') }}\nCreated at: {{ payload.timestamp | default('') }}\""
        incident_mapping:
          close_code:
            "": ""
