- name: Create an Incident
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        state: new
        short_description: "{{ payload.application | upper | default('') }}"
        description: |-
          impact: low
          urgency: low
          Account id: "{{ payload.account_id | default('') }}"
          Affected system: "{{ payload.context.display_name | default('') }}"
          Event type: "{{ payload.event_type | default('') }}"
          Bundle: "{{ payload.bundle | default('') }}"
          Created at: "{{ payload.timestamp | default('') }}"
