- name: Create an Incident
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: payload
      prompt: ""
      private: false
  tasks:
    - name: Dump all received variables
      debug:
        var: vars
    - name: Create the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_user }}"
          password: "{{ sn_password }}"
        state: new
        caller: "{{ sn_user }}"
        impact: 3
        urgency: 3
        short_description: "{{ payload.application | upper | default('') }}"
        description: |-
          impact: 3
          urgency: 3
          Account id: "{{ payload.account_id | default('') }}"
          Affected system: "{{ payload.context.display_name | default('') }}"
          Event type: "{{ payload.event_type | default('') }}"
          Bundle: "{{ payload.bundle | default('') }}"
          Created at: "{{ payload.timestamp | default('') }}"
